version: '3'

services:
  api:
    container_name: dictionary-backend
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file: .env
    command: npm run start:dev
    volumes:
      - ./:/app
    depends_on:
      - database
    ports:
      - '8080:8080/tcp'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  database:
    container_name: dictionarydb
    hostname: localhost
    image: postgres:16.3
    expose:
      - 5432
    environment:
      POSTGRES_DB: dictionary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    restart: always
